### ISSUE TITLE
ID020 - Error en la cabecera de las estadísticas del dashboard del profesor

### ISSUE THREAD

**Issue by ignsanalo** [yoadimpen/evidentia#40]
**Resumen**: La cabecera del panel de las estadísticas del profesor aparece con el título de la cabecera del panel de estadísticas de los alumnos.

**Prioridad**: Baja

**Fecha**: 14/01/2021

**Comment by josgongar12** [comment]
**Solución**: Se impuso una condición para que el cabecero mostrado aparezca según el rol que visualiza el Dashboard.
